language: ruby
cache: bundler

rvm:
  - &latest_ruby 2.7
  - 2.5

branches:
  only:
  - main
  - /^v\d+\.\d+\.\d+/

matrix:
  include:
  # GitHub Pages
  - rvm: 2.7.1
    env:
      - JEKYLL_VERSION="~> 3.9"
      - GITHUB_PAGES=1 # Only set on one build in matrix
  - rvm: *latest_ruby
    env: JEKYLL_VERSION="~> 4.0"

env:
  matrix:
  - JEKYLL_VERSION="~> 3.9"

git:
  depth: 1000

before_install:
  - gem update --system

install:
  - travis_retry script/bootstrap

script: script/cibuild
